### PR TITLE
fix: project name

### PR DESCRIPTION
**Pull request by caarlos0**
goreleaser does not have a `-` in its name... 

I renamed everything on code, but I think we should probably rename the repo too... 

that being said, not sure about the side-effects of this change, will understand if it breaks too many things and you want to take a different approach (or even do nothing at all).

### CODE REVIEW

**Comment by rawlingsj** [comment]
Howdy @caarlos0!  Sorry for the miss-spell :) Yeah happy to change it and will rename the repo too.  We'll need to change any jenkins-x-.yml that refers to the current name but I'm happy to do that and fix up anything else that breaks.

I've got a bit of work to get through these next couple of days but once all that is sorted lets merge and I'll fix anything that breaks.

**Comment by rawlingsj** [comment]
popping on hold for a cpl of days as this will need to schedule the release so I can fix any pipelines.
/hold

**Comment by caarlos0** [comment]
awesome, thanks @rawlingsj :)

**Comment by caarlos0** [comment]
gentle ping @rawlingsj

**Comment by rawlingsj** [comment]
@caarlos0 thanks for the reminder :). We've been upgrading our build infra and so needed to change the pipelines.  Sorry to be a pain but would you mind doing a rebase and removing the `jenkins-x.yml` as I can't resolve the conflict via the github UI please?

**Comment by caarlos0** [comment]
@rawlingsj no problem, done :)

**Comment by rawlingsj** [comment]
awesome - many thanks @caarlos0!
/lgtm

**Pull request merged**
